CREATE TABLE carrito.carritos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL,
    entra_object_id UUID NOT NULL,
    restaurante_id BIGINT,
    moneda VARCHAR(3) NOT NULL DEFAULT 'CLP',
    revision_contenido BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_carritos_identidad UNIQUE (tenant_id, entra_object_id),
    CONSTRAINT ck_carritos_restaurante CHECK (restaurante_id IS NULL OR restaurante_id > 0),
    CONSTRAINT ck_carritos_moneda CHECK (moneda = 'CLP'),
    CONSTRAINT ck_carritos_revision CHECK (revision_contenido >= 0 AND version >= 0)
);

CREATE TABLE carrito.lineas_carrito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrito_id BIGINT NOT NULL REFERENCES carrito.carritos(id) ON DELETE CASCADE,
    producto_id BIGINT NOT NULL,
    nombre_producto VARCHAR(200) NOT NULL,
    precio_unitario BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    CONSTRAINT uk_lineas_carrito_producto UNIQUE (carrito_id, producto_id),
    CONSTRAINT ck_lineas_producto CHECK (producto_id > 0),
    CONSTRAINT ck_lineas_nombre CHECK (length(trim(nombre_producto)) > 0),
    CONSTRAINT ck_lineas_precio CHECK (precio_unitario BETWEEN 0 AND 1000000000),
    CONSTRAINT ck_lineas_cantidad CHECK (cantidad BETWEEN 1 AND 99)
);
