CREATE TABLE pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    restaurante_id BIGINT NOT NULL,
    direccion_entrega VARCHAR(255) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    total BIGINT NOT NULL,
    moneda VARCHAR(3) NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_pedidos_estado CHECK (estado IN ('CREADO','CONFIRMADO','PREPARANDO','LISTO','EN_REPARTO','ENTREGADO','CANCELADO'))
);

CREATE TABLE lineas_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL REFERENCES pedidos(id),
    producto_id BIGINT NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario BIGINT NOT NULL,
    subtotal BIGINT NOT NULL,
    CONSTRAINT ck_lineas_pedido_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_lineas_pedido_precio CHECK (precio_unitario >= 0),
    CONSTRAINT ck_lineas_pedido_subtotal CHECK (subtotal >= 0)
);

CREATE INDEX idx_lineas_pedido_pedido ON lineas_pedido(pedido_id);
CREATE INDEX idx_pedidos_usuario ON pedidos(usuario_id);
