CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL,
    entra_object_id UUID NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    telefono VARCHAR(30),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_usuarios_identidad UNIQUE (tenant_id, entra_object_id),
    CONSTRAINT ck_usuarios_nombre CHECK (length(trim(nombre)) > 0),
    CONSTRAINT ck_usuarios_apellido CHECK (length(trim(apellido)) > 0),
    CONSTRAINT ck_usuarios_email CHECK (length(trim(email)) > 0)
);
