CREATE TABLE seguimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    estado_actual VARCHAR(30) NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_seguimientos_pedido UNIQUE (pedido_id),
    CONSTRAINT ck_seguimientos_estado CHECK (estado_actual IN (
        'RECIBIDO', 'EN_PREPARACION', 'LISTO', 'EN_CAMINO',
        'ENTREGADO', 'CANCELADO', 'RECHAZADO', 'DEVOLUCION'
    ))
);

CREATE TABLE seguimiento_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seguimiento_id BIGINT NOT NULL,
    estado VARCHAR(30) NOT NULL,
    ocurrido_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nota VARCHAR(500),
    CONSTRAINT fk_seguimiento_eventos_seguimiento
        FOREIGN KEY (seguimiento_id) REFERENCES seguimientos (id),
    CONSTRAINT ck_seguimiento_eventos_estado CHECK (estado IN (
        'RECIBIDO', 'EN_PREPARACION', 'LISTO', 'EN_CAMINO',
        'ENTREGADO', 'CANCELADO', 'RECHAZADO', 'DEVOLUCION'
    ))
);

CREATE INDEX idx_seguimiento_eventos_seguimiento_id
    ON seguimiento_eventos (seguimiento_id, ocurrido_en);
