spring.application.name=productos-service

server.port=8083

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pedidos360}
spring.datasource.username=${DB_USERNAME:pedidos360}
spring.datasource.password=${DB_PASSWORD:replace-me}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.flyway.default-schema=productos
spring.flyway.schemas=productos
spring.flyway.create-schemas=true

spring.jpa.properties.hibernate.default_schema=productos