CREATE TABLE repartidores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL,
    entra_object_id UUID NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    telefono VARCHAR(30),
    vehiculo VARCHAR(20) NOT NULL,
    zona VARCHAR(100),
    estado_disponibilidad VARCHAR(20) NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_repartidores_identidad UNIQUE (tenant_id, entra_object_id),
    CONSTRAINT ck_repartidores_nombre CHECK (length(trim(nombre)) > 0),
    CONSTRAINT ck_repartidores_vehiculo CHECK (vehiculo IN ('MOTO', 'BICICLETA', 'AUTO')),
    CONSTRAINT ck_repartidores_estado CHECK (estado_disponibilidad IN (
        'DISPONIBLE', 'OCUPADO', 'EN_CAMINO', 'EN_PAUSA',
        'DESCONECTADO', 'INACTIVO', 'SUSPENDIDO'
    ))
);

CREATE TABLE repartidor_asignaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repartidor_id BIGINT NOT NULL,
    pedido_id BIGINT NOT NULL,
    estado VARCHAR(20) NOT NULL,
    asignada_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nota VARCHAR(500),
    CONSTRAINT uk_asignaciones_pedido UNIQUE (pedido_id),
    CONSTRAINT fk_asignaciones_repartidor
        FOREIGN KEY (repartidor_id) REFERENCES repartidores (id),
    CONSTRAINT ck_asignaciones_estado CHECK (estado IN (
        'ASIGNADA', 'EN_CAMINO', 'ENTREGADA', 'CANCELADA'
    ))
);

CREATE INDEX idx_asignaciones_repartidor_id
    ON repartidor_asignaciones (repartidor_id, asignada_en);
