CREATE TABLE pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    monto BIGINT NOT NULL,
    moneda VARCHAR(3) NOT NULL,
    metodo VARCHAR(10) NOT NULL,
    estado VARCHAR(10) NOT NULL,
    clave_idempotencia VARCHAR(80) NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_pagos_idempotencia UNIQUE (clave_idempotencia),
    CONSTRAINT ck_pagos_metodo CHECK (metodo IN ('TARJETA','EFECTIVO')),
    CONSTRAINT ck_pagos_estado CHECK (estado IN ('PENDIENTE','APROBADO','RECHAZADO')),
    CONSTRAINT ck_pagos_monto CHECK (monto >= 0)
);

CREATE INDEX idx_pagos_pedido ON pagos(pedido_id);
CREATE INDEX idx_pagos_usuario ON pagos(usuario_id);
