CREATE TABLE restaurantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(500),
    direccion VARCHAR(255),
    estado VARCHAR(20) NOT NULL,

    CONSTRAINT chk_restaurantes_estado
        CHECK (estado IN ('ABIERTO', 'CERRADO', 'INACTIVO'))
);